---
name: PDF-Kit
version: v1.0.4
author:
  - 'Shawn H Corey <SHCOREY@cpan.org>'
abstract: A collection of subroutines for PDF::API2.
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
build_requires:
  Test::More: 0
provides:
  PDF::Kit:
    file: lib/PDF/Kit.pm
    version: v1.0.4
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
